### ISSUE TITLE
Not compatible with Meteor 0.9.0 or Later

### ISSUE THREAD

**Issue by adoyen** [cmather/meteor-handlebars-server#21]
Hello,
After upgrade to Meteor 0.9.0.1, this package is not compatible anymore.

> $ meteor add cmather:handlebars-server
>  added cmather:handlebars-server at version 1.2.0
> cmather:handlebars-server: INCOMPATIBLE WITH METEOR 0.9.0 OR LATER

And when launching application, I receive this errors :

> W20140830-11:37:10.039(2)? (STDERR) The package cmather:handlebars-server at 1.2.0 is incompatible with Meteor 0.9.0 or later. 
> W20140830-11:37:10.041(2)? (STDERR) If a new, compatible version of this package exists, running 'meteor update' should cause you to update. 
> W20140830-11:37:10.087(2)? (STDERR) 
> W20140830-11:37:10.089(2)? (STDERR) ~/.meteor/packages/meteor-tool/.1.0.26.1owm6lu++os.linux.x86_64+web.browser+web.cordova/meteor-tool-os.linux.x86_64/dev_bundle/lib/node_modules/fibers/future.js:173
> W20140830-11:37:10.090(2)? (STDERR)                       throw(ex);
> W20140830-11:37:10.090(2)? (STDERR)                             ^
> W20140830-11:37:10.091(2)? (STDERR) ReferenceError: OriginalHandlebars is not defined
> W20140830-11:37:10.092(2)? (STDERR)     at app/server/mail-templates/mail-helpers.js:1:36
> W20140830-11:37:10.092(2)? (STDERR)     at app/server/mail-templates/mail-helpers.js:11:3
> W20140830-11:37:10.092(2)? (STDERR)     at ./.meteor/local/build/programs/server/boot.js:161:10
> W20140830-11:37:10.093(2)? (STDERR)     at Array.forEach (native)
> W20140830-11:37:10.093(2)? (STDERR)     at Function._.each._.forEach (./.meteor/packages/meteor-tool/.1.0.26.1owm6lu++os.linux.x86_64+web.browser+web.cordova/meteor-tool-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
> W20140830-11:37:10.093(2)? (STDERR)     at ./.meteor/local/build/programs/server/boot.js:82:5
> => Exited with code: 8

I tried also installing it using meteorite but this is not working either.

**Comment by jfer77** [comment]
same problem here

**Comment by isAlmogK** [comment]
Having the same issues

**Comment by cmather** [comment]
sorry, try again. i had published an incorrect version. it should work now.

**Comment by isAlmogK** [comment]
No still not working I did 

meteor update cmather:handlebars-server  
Refreshing package metadata. This may take a moment.
All your package dependencies are already up to date.

and I still get The package cmather:handlebars-server at 1.2.0 is incompatible with Meteor 0.9.0 or later.

**Comment by adoyen** [comment]
Working for me.
I removed the package and reinstalled it and it worked like a charm with version 2.0.0.

> $ meteor remove cmather:handlebars-server
> Removed top-level dependency on cmather:handlebars-server.
> $ meteor add cmather:handlebars-server
> Refreshing package metadata. This may take a moment.
>  downloading cmather:handlebars-server at version 2.0.0 ...  done
>  added cmather:handlebars-server at version 2.0.0
>  added handlebars at version 1.0.0

As usual, Chris, you are very fast to solve issues.
Thanks a lot.

**Comment by isAlmogK** [comment]
@adoyen thanks everything is working now. Chris thanks for the fast update

**Comment by kiewietr** [comment]
running meteor update cmather:handlebars-server fixed it for me as well. Thanks!
